apiVersion : apps/v1
kind: Deployment
metadata:
  name: ahmedbhamppipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahmedbhamppipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: ahmedbhamppipelinesjavascriptdocker 
    spec:
      containers:
        - name: ahmedbhamppipelinesjavascriptdocker 
          image: k8strainingbham.azurecr.io/ahmedbhamppipelinesjavascriptdocker
          ports:
          - containerPort: 8080