apiVersion: v1
kind: Service
metadata:
  name: javascript-docker
  namespace: javascript-docker
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: javascript-docker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000